### ISSUE TITLE
Feature Request: Modularize portal gun

### ISSUE THREAD

**Issue by Prymaldark** [Bilka2/Portals#2]
Could the portal gun be made into an equipment module, to be placed in armors? This could then be activated with a keybinding, which the user may select in the normal keybinding menu.

**Comment by Bilka2** [comment]
What would the "activated" portal gun do?
If you "just" want to be able to place the portals with a certain keybinding, this should also be possible with a normal item. I could for example teleport the item from your main inventory into your hand on keypress.

**Comment by Prymaldark** [comment]
By activated, I was referring to the triggers that placed the portals. My thought was then it would not be an item plugging around in an inventory, but something that can be dropped in the armor. That, or I've also wondered about adding a new slot, akin to the tool slot, that would be used for the portal gun; though that is more for a mod I've been working on. 

Whatever you think works.

**Comment by Bilka2** [comment]
It is sadly not possible to place entities on keypress because the api does not provide me with a way to directly get the mouse position of the player. I personally also do not see the benefit of having an item in your power armor which is extremely limited on space instead of in the main inventory. 

I'll think about adding a keybind that teleports the portal gun into the player cursor from the main inventory.
